# Generated by Django 5.1.2 on 2024-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_product_quantity_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Medicine', 'Medicine')], max_length=100),
        ),
    ]
